name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
   
    - name: Setup 
      run: |
        sudo apt-get update && sudo apt-get install -y make

    - name: Build
      run: |
       make autoortho_lin.bin 

    - name: Save artifact
      uses: actions/upload-artifact@v3
      with:
        name: linbin
        path: autoortho_lin.bin


  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
   
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Setup 
      run: |
          #choco --yes install winfsp
          python -m pip install -U pytest 
          # Windows OS package install ecosystem is sketchy and broken.  Just test min stuff ...
          python -m pip install -U -r requirements-win.txt
          python -m pip install -U -r requirements-build.txt

    - name: Build
      run: |
        make autoortho_win.exe
        make autoortho_win.zip ZIP="7z a"

    - name: Save artifact
      uses: actions/upload-artifact@v3
      with:
        name: winbin
        path: |
          autoortho_win.exe
          autoortho_win.zip
  
  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
   
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Setup 
      run: |
          brew install python-tk@3.10
          python3.10 -m pip install -U -r requirements.txt
          python3.10 -m pip install -U -r requirements-build.txt

    - name: Build
      run: |
        ls /Library/Frameworks/Python.framework/Versions/3.10/lib/tcl8.6
        ls /Library/Frameworks/Python.framework/Versions/3.10/lib/tcl8.5
        ls /Library/Frameworks/Python.framework/Versions/3.10/lib/
        make autoortho_osx.bin

    - name: Save artifact
      uses: actions/upload-artifact@v3
      with:
        name: macosbin
        path: |
          autoortho_osx.bin
